### ISSUE TITLE
Don't include the lib/pythonX.Y/test folder

### ISSUE THREAD

**Issue by brechtm** [pybee/Python-Apple-support#4]
... to reduce the size of the distribution.

For Python 3.5 for example, the test folder is 54MB, which is about 40% of the total distribution size.

**Comment by freakboy3742** [comment]
Thanks - the build system has some code to strip out the test directory, as well as a few other big files that aren't needed. If the current distribution contains those files, I must have inadvertently  commented that code out when doing the most recent build. 

I'll keep an eye on it for the next release.

**Comment by freakboy3742** [comment]
This has now been addressed in the latest builds.

**Comment by brechtm** [comment]
I'm still seeing tests being included in the build produced by my updated 3.5-zlib branch. The output of 

    tar tf dist/Python-3.5-macOS-support.b3.tar.gz | grep "/test/"

is attached: [3.5-zlib-test.txt](https://github.com/pybee/Python-Apple-support/files/793254/3.5-zlib-test.txt)
